### PR TITLE
Manuscript style

### PR DESCRIPTION
**Pull request by gaffa27**
This adds a nanuscript style for writing and editing.

It is based heavily on Novel mode, the primary differences are:

 - it uses a fixed-width font for both editing and rendering
 - preview mode output is slightly more compact

unfortunately it includes acommit to get my local build working - hopely you can cherry-pick around that, or i can try regenerate the pull request with out that commit.

### CODE REVIEW

**Comment by lmparppei** [comment]
Wow, thank you! Could you make this pull request to the newly-created branch `manuscript-style`, so I can check it separately from main? (I'm *still* very bad with git, he he)

**Comment by gaffa27** [comment]
I've updated the pull request.. Please let me know if there are any issues. (i'm a a Git newbie too!)

**Comment by lmparppei** [comment]
There are some indentation issues.

image
image

I'm not sure if this is by design, but at least the tutorial says (like the one for Novel Mode) that paragraphs with a line break between them should not be indented. I have no recollection at this point *how* this happens in Novel Mode, but I think this is the part causing the issue:
```
indent-split-elements: false;
unindent-fresh-paragraphs: false;
```

**Comment by gaffa27** [comment]
I've just gotten myself into git hell.  I am addressing your comments.

**Pull request merged**
